#!/bin/bash
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co14.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co15.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co16.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1co9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1jo1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1jo2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1jo3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1jo4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1jo5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1pe1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1pe2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1pe3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1pe4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1pe5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1th1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1th2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1th3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1th4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1th5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1ti1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1ti2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1ti3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1ti4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1ti5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/1ti6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2co9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2jo1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2pe1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2pe2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2pe3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2th1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2th2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2th3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2ti1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2ti2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2ti3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/2ti4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/3jo1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act14.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act15.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act16.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act17.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act18.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act19.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act20.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act21.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act22.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act23.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act24.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act25.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act26.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act27.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act28.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/act9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/col1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/col2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/col3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/col4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/eph1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/eph2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/eph3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/eph4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/eph5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/eph6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/gal1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/gal2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/gal3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/gal4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/gal5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/gal6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/heb9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/jam1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/jam2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/jam3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/jam4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/jam5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh14.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh15.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh16.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh17.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh18.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh19.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh20.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh21.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/joh9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/jud1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk14.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk15.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk16.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk17.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk18.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk19.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk20.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk21.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk22.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk23.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk24.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/luk9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar14.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar15.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar16.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mar9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat14.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat15.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat16.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat17.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat18.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat19.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat20.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat21.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat22.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat23.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat24.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat25.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat26.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat27.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat28.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/mat9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/phi1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/phi2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/phi3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/phi4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/phm1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev14.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev15.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev16.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev17.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev18.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev19.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev20.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev21.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev22.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rev9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom10.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom11.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom12.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom13.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom14.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom15.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom16.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom3.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom4.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom5.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom6.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom7.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom8.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/rom9.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/tit1.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/tit2.pdf
wget https://www.scripture4all.org/OnlineInterlinear/NTpdf/tit3.pdf
